version: '3.8'

services:
  app:
    image: oussama2306/tp-foyer:${TAG}
    container_name: spring-application
    ports:
      - "8089:8089"  # Maps port 8089 on host to 8089 on container
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer

  db:
    image: mysql:8.0
    container_name: tp-foyer-database
    environment:
      MYSQL_ROOT_PASSWORD: ""  
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local
