#version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: db

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: ghaythsel404/tp-foyer:1.0.0
    container_name: app_foyer
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: null
      spring.jpa.hibernate:ddl-auto: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true

volumes:
  db_data:
